logo: https://avatars.githubusercontent.com/u/57609353
description: Hi!  I'm a computer engineering student at UPenn interested in robotics and service.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jemoji
